### ISSUE TITLE
How about running `apt update` at the start?

### ISSUE THREAD

**Issue by axelbdt** [piku/piku-bootstrap#7]
Hi,
I provisioned a VPS that had empty package lists, so the bootstrap failed with `E: Unable to locate package git`. How about running `apt update` at the start of the bootstrapping process to avoid this minor hiccup?
Cheers

**Comment by axelbdt** [comment]
I was running `./piku-bootstrap` instead of `./piku-bootstrap install`, sorry for the noise.

**Comment by chr15m** [comment]
All good, no problem. Do you think there is anything I could change to make the process clearer or less error prone?

**Comment by axelbdt** [comment]
I have just edited the previous comment, I think the `apt update` is in order after all.

**Comment by chr15m** [comment]
OK great, will put together a patch.

**Comment by axelbdt** [comment]
Thank you.

P.S. I've just stumbled on rogule, what a delighful project! :)

**Comment by chr15m** [comment]
Glad you enjoy it, thanks for the kind words!

**Comment by chr15m** [comment]
Hi Axel, I realized that `apt update` should already be run because [`update_cache` is set to true](https://github.com/piku/piku-bootstrap/blob/main/playbooks/piku.yml#L35). Here are the docs about `update_cache`:

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#parameter-update_cache

I'm not sure how this ran but you still got the missing git dep. Very strange. Let me know if you have more info on the VPS you deployed so we can get to the bottom of it.

**Comment by axelbdt** [comment]
This line from the `piku-bootstrap` script seems to be the problem.
https://github.com/piku/piku-bootstrap/blob/87fa68bece6516eca6aaa3282ea2da94d568a0f0/piku-bootstrap#L40

It seems we don't reach the ansible part, so the `apt cache update` could be added at the very beginning of the shell script. What do you think?

**Comment by chr15m** [comment]
Ah yes, good catch. I'll think about the best way to fix this.

**Comment by chr15m** [comment]
I think maybe the best thing to do would be run the apt update only if the "unable to locate package" error occurs.
